apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: preye
  name: preye
spec:
  containers:
  - image: jenkins/jenkins:latest
    name: preye-jenkins
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
